// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPktzJOT1ZAcC9u6VydI1RA9-HeeWCpyI',
    appId: '1:295414608301:web:1ae700295bc34673737124',
    messagingSenderId: '295414608301',
    projectId: 'u-marked',
    authDomain: 'u-marked.firebaseapp.com',
    storageBucket: 'u-marked.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVNug_AW-i5HFi1WVdFH-Fkd0u_EIoEp8',
    appId: '1:295414608301:android:3b5faa947d0f3159737124',
    messagingSenderId: '295414608301',
    projectId: 'u-marked',
    storageBucket: 'u-marked.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgJtkQDvKx3bNUEzex8WXanv8AJcDVmWw',
    appId: '1:295414608301:ios:d266bb1ebd5fa48c737124',
    messagingSenderId: '295414608301',
    projectId: 'u-marked',
    storageBucket: 'u-marked.appspot.com',
    iosClientId: '295414608301-cf8q4c5gsu3n76ooml0r3trfp48mn555.apps.googleusercontent.com',
    iosBundleId: 'com.example.uMarked',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgJtkQDvKx3bNUEzex8WXanv8AJcDVmWw',
    appId: '1:295414608301:ios:d266bb1ebd5fa48c737124',
    messagingSenderId: '295414608301',
    projectId: 'u-marked',
    storageBucket: 'u-marked.appspot.com',
    iosClientId: '295414608301-cf8q4c5gsu3n76ooml0r3trfp48mn555.apps.googleusercontent.com',
    iosBundleId: 'com.example.uMarked',
  );
}
